# Generated by Django 5.2.17 on 2026-09-28 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, default="")),
                ("target_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="not_started",
                        max_length=15,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "progress_percent",
                    models.PositiveIntegerField(default=0, help_text="0-100"),
                ),
                ("coach_notes", models.TextField(blank=True, default="")),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgressEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "rating",
                    models.PositiveIntegerField(
                        blank=True, help_text="Current chess rating", null=True
                    ),
                ),
                (
                    "tactics",
                    models.PositiveIntegerField(
                        blank=True, help_text="Tactics skill 1-10", null=True
                    ),
                ),
                (
                    "opening_knowledge",
                    models.PositiveIntegerField(
                        blank=True, help_text="Opening knowledge 1-10", null=True
                    ),
                ),
                (
                    "middlegame",
                    models.PositiveIntegerField(
                        blank=True, help_text="Middlegame skill 1-10", null=True
                    ),
                ),
                (
                    "endgame",
                    models.PositiveIntegerField(
                        blank=True, help_text="Endgame skill 1-10", null=True
                    ),
                ),
                (
                    "calculation",
                    models.PositiveIntegerField(
                        blank=True, help_text="Calculation ability 1-10", null=True
                    ),
                ),
                (
                    "positional",
                    models.PositiveIntegerField(
                        blank=True, help_text="Positional understanding 1-10", null=True
                    ),
                ),
                (
                    "time_management",
                    models.PositiveIntegerField(
                        blank=True, help_text="Time management 1-10", null=True
                    ),
                ),
                ("strengths", models.TextField(blank=True, default="")),
                ("weaknesses", models.TextField(blank=True, default="")),
                ("next_goals", models.TextField(blank=True, default="")),
                ("coach_comments", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_entries",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progress Entry",
                "verbose_name_plural": "Progress Entries",
                "ordering": ["-date"],
            },
        ),
    ]
