# Generated by Django 5.2.17 on 2026-09-28 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("coaching", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, default="", max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="students/"),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("whatsapp", models.CharField(blank=True, default="", max_length=20)),
                ("address", models.TextField(blank=True, default="")),
                ("school", models.CharField(blank=True, default="", max_length=200)),
                (
                    "school_class",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Class/Grade",
                    ),
                ),
                ("joining_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("on_break", "On Break"),
                            ("graduated", "Graduated"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                (
                    "coaching_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("group", "Group"),
                            ("both", "Both"),
                        ],
                        default="individual",
                        max_length=15,
                    ),
                ),
                (
                    "preferred_mode",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("both", "Both"),
                        ],
                        default="offline",
                        max_length=10,
                    ),
                ),
                (
                    "chess_level",
                    models.CharField(
                        choices=[
                            ("absolute_beginner", "Absolute Beginner"),
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("tournament", "Tournament Player"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "fide_id",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="FIDE ID"
                    ),
                ),
                (
                    "fide_rating",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="FIDE Rating"
                    ),
                ),
                (
                    "chess_com_username",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Chess.com Username",
                    ),
                ),
                (
                    "lichess_username",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Lichess Username",
                    ),
                ),
                ("strengths", models.TextField(blank=True, default="")),
                ("weaknesses", models.TextField(blank=True, default="")),
                ("chess_goals", models.TextField(blank=True, default="")),
                ("preferred_openings", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="coaching.batch",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("guardian", "Guardian"),
                            ("other", "Other"),
                        ],
                        default="father",
                        max_length=15,
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("whatsapp", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "preferred_communication",
                    models.CharField(
                        choices=[
                            ("phone", "Phone Call"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                        ],
                        default="whatsapp",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True, related_name="parents", to="students.student"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
