# Generated by Django 5.2.17 on 2026-09-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, default="")),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "icon",
                    models.CharField(blank=True, default="bi-award", max_length=50),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-date"],
            },
        ),
        migrations.CreateModel(
            name="CoachingProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "features",
                    models.TextField(
                        blank=True, default="", help_text="One feature per line"
                    ),
                ),
                (
                    "price_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='e.g. "₹3000/month" or "Contact for pricing"',
                        max_length=100,
                    ),
                ),
                ("is_popular", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CoachingService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="bi-trophy",
                        help_text="Bootstrap icon class",
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academy_name",
                    models.CharField(default="Chess Academy", max_length=200),
                ),
                ("coach_name", models.CharField(default="Coach", max_length=200)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                ("about", models.TextField(blank=True, default="")),
                (
                    "tagline",
                    models.CharField(
                        blank=True, default="Master the Game of Kings", max_length=300
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("whatsapp", models.CharField(blank=True, default="", max_length=20)),
                ("address", models.TextField(blank=True, default="")),
                ("website_url", models.URLField(blank=True, default="")),
                ("facebook_url", models.URLField(blank=True, default="")),
                ("instagram_url", models.URLField(blank=True, default="")),
                ("youtube_url", models.URLField(blank=True, default="")),
                ("twitter_url", models.URLField(blank=True, default="")),
                ("linkedin_url", models.URLField(blank=True, default="")),
                ("currency_symbol", models.CharField(default="₹", max_length=5)),
                ("currency_code", models.CharField(default="INR", max_length=5)),
                (
                    "fee_reminder_template",
                    models.TextField(
                        blank=True,
                        default="Hello {parent_name}, this is a friendly reminder that the chess coaching fee of ₹{amount} for {student_name} is pending. Due date: {due_date}. Thank you.",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        blank=True, default="Elevate Your Chess Game", max_length=300
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        blank=True,
                        default="Expert coaching for players of all levels. From beginners to tournament champions.",
                    ),
                ),
                (
                    "hero_cta_text",
                    models.CharField(
                        blank=True, default="Book a Free Trial", max_length=100
                    ),
                ),
                (
                    "coach_title",
                    models.CharField(
                        blank=True, default="FIDE Rated Coach", max_length=200
                    ),
                ),
                (
                    "coach_photo",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                ("coach_bio", models.TextField(blank=True, default="")),
                (
                    "coach_experience",
                    models.CharField(
                        blank=True, default="10+ Years Experience", max_length=200
                    ),
                ),
                (
                    "coach_rating",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "coach_students_trained",
                    models.CharField(blank=True, default="500+", max_length=100),
                ),
                (
                    "how_it_works",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text='JSON list of steps: [{"title":"...", "description":"..."}]',
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        default="Student",
                        help_text="e.g. Student, Parent, Tournament Player",
                        max_length=100,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
