# Generated by Django 5.2.17 on 2026-09-28 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tournament_name", models.CharField(max_length=300)),
                ("date", models.DateField()),
                ("location", models.CharField(blank=True, default="", max_length=200)),
                ("total_rounds", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "score",
                    models.CharField(
                        blank=True, default="", help_text="e.g. 5.5/7", max_length=20
                    ),
                ),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "total_participants",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("rating_before", models.PositiveIntegerField(blank=True, null=True)),
                ("rating_after", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "performance_rating",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("highlights", models.TextField(blank=True, default="")),
                ("coach_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_results",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
