# Generated by Django 5.2.17 on 2026-09-28 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("coaching", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="chessclass",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes",
                to="coaching.batch",
            ),
        ),
        migrations.AddField(
            model_name="chessclass",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="classes", to="students.student"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="chess_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="coaching.chessclass",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("chess_class", "student")},
        ),
    ]
