# Generated by Django 5.2.17 on 2026-09-28 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=200)),
                (
                    "parent_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("phone", models.CharField(max_length=20)),
                ("whatsapp", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "current_level",
                    models.CharField(
                        choices=[
                            ("absolute_beginner", "Absolute Beginner"),
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("tournament", "Tournament Player"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "current_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="FIDE/online rating if available",
                        null=True,
                    ),
                ),
                (
                    "preferred_mode",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=10,
                    ),
                ),
                (
                    "preferred_schedule",
                    models.TextField(
                        blank=True, default="", help_text="Preferred days and times"
                    ),
                ),
                ("coaching_goal", models.TextField(blank=True, default="")),
                ("message", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("trial_scheduled", "Trial Scheduled"),
                            ("interested", "Interested"),
                            ("converted", "Converted"),
                            ("not_interested", "Not Interested"),
                            ("follow_up", "Follow Up Later"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="website",
                        help_text="How did they find us?",
                        max_length=100,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Internal notes"
                    ),
                ),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "converted_student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_enquiry",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Enquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnquiryFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField()),
                ("next_follow_up", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="enquiries.enquiry",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
