# Generated by Django 5.2.17 on 2026-09-28 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("announcements", "0001_initial"),
        ("coaching", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="announcements",
                to="coaching.batch",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="announcements", to="students.student"
            ),
        ),
    ]
